org: brandutan
app: compute-weights-app
service: compute-weights

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-1
  memorySize: 2048
  logRetentionInDays: 30
  lambdaHashingVersion: 20201221

functions:
  ComputeWeights:
    handler: compute_weights.compute_weights
    timeout: 15
    events:
      - http:
          path: /compute_weights
          method: post
          cors: true
  GetHistoricalPositions:
    handler: compute_historical_positions.compute_position
    timeout: 15
    events:
      - http:
          path: /compute_position
          method: post
          cors: true

custom:
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-api-gateway-throttling

package:
  patterns:
    - '!node_modules/**'
