service: bpm-backend-microservices
frameworkVersion: "2"
useDotenv: true

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-1
  memorySize: 2048
  logRetentionInDays: 30
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${env:BUCKET}/*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${env:BUCKET}"
  environment:
    BUCKET: ${env:BUCKET}
    COIN_FILE_NAMES: ${env:COIN_FILE_NAMES}
    USDT_PRICE_FILE_NAME: ${env:USDT_PRICE_FILE_NAME}
    ETH_PRICE_FILE_NAME: ${env:ETH_PRICE_FILE_NAME}
    BTC_PRICE_FILE_NAME: ${env:BTC_PRICE_FILE_NAME}

functions:
  ComputeWeights:
    handler: compute_weights.compute_weights
    timeout: 30
    memorySize: 512
    name: ComputeWeights
    events:
      - http:
          path: /compute_weights
          method: post
          cors: true
  GetHistoricalPositions:
    handler: compute_historical_positions.compute_position
    timeout: 30
    memorySize: 3072
    name: GetHistoricalPositions
    events:
      - http:
          path: /compute_position
          method: post
          cors: true
  ComputePnL:
    handler: compute_pnl.compute_pnl
    timeout: 30
    memorySize: 3072
    name: ComputePnL
    events:
      - http:
          path: /compute_pnl
          method: post
          cors: true
  GetAllTrades:
    handler: get_all_trades.get_all_trades
    timeout: 30
    memorySize: 2048
    name: GetAllTrades
    events:
      - http:
          path: /get_all_trades
          method: post
          cors: true
  GetTickers:
    handler: get_valid_tickers.get_valid_tickers
    timeout: 30
    memorySize: 1024
    name: GetTickers
    events:
      - http:
          path: /get_valid_tickers
          method: get
          cors: true

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
custom:
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  # - serverless-offline
  - serverless-python-requirements
  - serverless-api-gateway-throttling
  - serverless-prune-plugin

package:
  patterns:
    - "!node_modules/**"
